Husky+

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,10 @@
-bun
+echo "Running pre-commit hook"
+
+bun run format
+
+if [ $? -ne 0 ]; then
+  echo "Formatting failed"
+  exit 1
+fi
+
+git add -u
